Train:
  batch_size: 1
  d_learning_rate: 0.00001
  d_momentum: 0.95
  d_reg: 0.00001
  g_learning_rate: 0.001
  g_momentum: 0.95
  g_reg: 0.00001
  coeff_adv: 0.8
  coeff_pw: 0.2
  epochs: 10

data:
  save_best: True